### ISSUE TITLE
ICDAR 2011 dataset

### ISSUE THREAD

**Issue by williamking5** [VinhLoiIT/vietnamese-htr#5]
Hi, I noticed that you use ICDAR 2011 dataset in the repository, but I found it's tricky to download the dataset.

I tried to register an account on ICDAR 2011 Robust Reading Competition official website but didn't receive the email with passwords.

Do you have any ideas?

I would be really appreciated if you could give me some suggestions! Thank you very much.

**Comment by VinhLoiIT** [comment]
Hi @williamking5,

Are you talking about [RIMES](http://www.a2ialab.com/doku.php?id=rimes_database:start) dataset?

I've already added bash scripts to download the dataset, which is located at `data/rimes_line.sh` and `data/rimes_word.sh`. All you need to do into jump into the `data` folder and run the script (if you use Linux-based, e.g. Ubuntu) as follows.
```bash
cd data
./rimes_word.sh
```
or
```bash
cd data
./rimes_line.sh
```

Unfortunately, I haven't tested it on the Windows system yet that it might not work there. In that case, you might have to download the data directly on Google Cloud.
- [RIMES Line dataset](https://docs.google.com/uc?export=download&id=1MRcSXxMJoGKmKtmCgohKLWpu6q3rsXX5)
- [RIMES Word dataset](https://drive.google.com/drive/folders/1z-lR9j9fTFb6gXNK6QbGQenDLp5eEIRi?usp=sharing)

**Note**:
- The `RIMES Line` dataset has some wrong-labeled lines that you need to update the ground-truth in the XML file manually as described in `data/RIMES_Line//training_2011.patch`
- I am not responsible for any wrong-using data for other purposes than research.

Hope this would help. Thank you.

**Comment by VinhLoiIT** [comment]
I believe that you should use your company's or school's email address (not Gmail or something like that), to register for an account on the site. Then, they might provide your account's password within a day in my case.

**Comment by williamking5** [comment]
I will try it again, thank you very much!

**Comment by VinhLoiIT** [comment]
You're welcome.

I'll close the issue for now.

**Comment by williamking5** [comment]
Hi VinhLoiIT, I tried again with my university email yesterday, but failed. I have searched many websites, and found no shared links. Could you please share the dataset with me? Thank you very much! My email is williamking5@foxmail.com
